### ISSUE TITLE
Any chance for a NEMA 17 version?

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [Amekyras/tulip#1]
https://www.printables.com/model/917398-voron-v02-nema-17
Basically this mod allows installing NEMA 17 motors at the expense of taking up 6 more millimeters of space in the back. Would be cool if it supports pins and double shear.

**Comment by Driftrotor** [comment]
we have been looking at this to see how suitable it is, so far it looks promising but has the disadvantage of making the chamber hard to seal as it protrudes out of the back of the printer. also the standard bowden plate in between the AB motor mounts will not be able to be used.

**Comment by Ataraxia-Mechanica** [comment]
I actually have designed a custom back plate to seal it, works pretty well but it is made in blender instead of cad.
![image](https://github.com/user-attachments/assets/b5640292-730a-43ce-88c3-1b07c0dae477)

**Comment by Driftrotor** [comment]
we have added in a Beta Test for the Nema 17 AB Motor Mounts for testing. any feedback would be great

**Comment by Ataraxia-Mechanica** [comment]
Uh oh
I only have 20mm shaft motors and it's kinda hard to find long shaft high current motors where I live

**Comment by Driftrotor** [comment]
no worries, to be fair there are plenty of good nema 14's out on the market and lots of users report good performance from these.
these might be more readily available where you are too.
